'use client';
import dynamic from 'next/dynamic';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,ArrowRight,Compass,BookOpen,Bookmark,MapPin,Move,Plus,Minus,RotateCcw,Sparkles,Check,X,Award,ExternalLink,Globe2} from 'lucide-react';
import {destinations,questions} from '@/lib/destinations';
import {credits} from '@/lib/credits';
const MalaysiaScene=dynamic(()=>import('@/components/MalaysiaScene'),{ssr:false,loading:()=> <div className="scene-loading"><Compass size={34}/><span>Bringing Malaysia a little closer…</span></div>});
const STORAGE_KEY='kita-malaysia-passport-v1';
type Progress={stamps:string[];best:number|null};
type ModalKind='story'|'passport'|'quiz'|'credits'|null;
type PageTool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};

function Modal({children,onClose,label,className=''}:{children:React.ReactNode;onClose:()=>void;label:string;className?:string}){
 const dialog=useRef<HTMLDialogElement>(null);const closeRef=useRef(onClose);
 useEffect(()=>{closeRef.current=onClose},[onClose]);
 useEffect(()=>{const element=dialog.current!;const previous=document.body.style.overflow;element.showModal();document.body.style.overflow='hidden';return()=>{element.close();document.body.style.overflow=previous}},[]);
 return <dialog ref={dialog} aria-label={label} className={`modal ${className}`} onCancel={e=>{e.preventDefault();closeRef.current()}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeRef.current()}}}><button className="modal-close" aria-label="Close dialog" onClick={onClose}><X size={20}/></button>{children}</dialog>;
}

function Quiz({onComplete,onPassport}:{onComplete:(score:number)=>void;onPassport:()=>void}){
 const [step,setStep]=useState(0);const [answers,setAnswers]=useState<number[]>([]);const [finished,setFinished]=useState(false);
 const question=questions[step],answered=answers[step]!==undefined;
 const score=answers.reduce((total,answer,index)=>total+(answer===questions[index].answer?1:0),0);
 const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus()},[step,finished]);
 if(finished)return <div className="quiz-finish"><div className="award-icon"><Award size={42}/></div><span className="eyebrow-small">A LITTLE MORE MALAYSIA, A LITTLE MORE YOU</span><h2 ref={heading} tabIndex={-1}>{score===5?'You know your Malaysia!':score>=3?'A curious mind travels far.':'Every discovery is a beginning.'}</h2><div className="quiz-score">{score}<span>/ 5</span></div><p>{score===5?'Five discoveries, five right answers. Keep that curiosity going.':'There’s always another story to discover. Explore the map and give it another go.'}</p><div className="modal-actions"><button className="primary-button" onClick={onPassport}>View my passport <ArrowRight size={17}/></button><button className="text-button" onClick={()=>{setAnswers([]);setStep(0);setFinished(false)}}>Try again <RotateCcw size={15}/></button></div></div>;
 return <div className="quiz-content"><span className="eyebrow-small">THE MALAYSIA QUIZ</span><div className="quiz-progress-label"><span>Curiosity looks good on you.</span><span>{step+1} / {questions.length}</span></div><div className="quiz-progress" aria-label={`Question ${step+1} of ${questions.length}`}>{questions.map((_,i)=><span key={i} className={i<=step?'filled':''}/>)}</div><h2 ref={heading} tabIndex={-1}>{question.question}</h2><div className="quiz-options">{question.options.map((option,i)=><button key={option} disabled={answered} onClick={()=>setAnswers(current=>[...current,i])} className={`quiz-option ${answered?(i===question.answer?'correct':i===answers[step]?'incorrect':''):''}`}><span>{String.fromCharCode(65+i)}</span>{option}{answered&&i===question.answer&&<Check size={19}/>}</button>)}</div>{answered&&<div className={`answer-note ${answers[step]===question.answer?'right':'wrong'}`} role="status"><strong>{answers[step]===question.answer?'That’s right!':'A new thing to know.'}</strong><p>{question.explanation}</p></div>}<button className="primary-button quiz-next" disabled={!answered} onClick={()=>{if(step===questions.length-1){setFinished(true);onComplete(score)}else setStep(step+1)}}>{step===questions.length-1?'See my result':'Next question'}<ArrowRight size={17}/></button></div>;
}

export default function Explorer(){
 const [selected,setSelected]=useState('kl');const [command,setCommand]=useState({type:'reset',key:0});const [modal,setModal]=useState<ModalKind>(null);
 const [progress,setProgress]=useState<Progress>({stamps:[],best:null});const [loaded,setLoaded]=useState(false);const [storageAvailable,setStorageAvailable]=useState(true);const [resetConfirm,setResetConfirm]=useState(false);
 const currentState=useRef({selected,progress});useEffect(()=>{currentState.current={selected,progress}},[selected,progress]);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const value=JSON.parse(raw);setProgress({stamps:Array.isArray(value.stamps)?[...new Set<string>(value.stamps.filter((id:unknown)=>typeof id==='string'&&destinations.some(d=>d.id===id)))]:[],best:Number.isInteger(value.best)&&value.best>=0&&value.best<=5?value.best:null});}}catch{setStorageAvailable(false)}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));setStorageAvailable(true)}catch{setStorageAvailable(false)}},[progress,loaded]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:PageTool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tools:PageTool[]=[{name:'open_destination_story',description:'Select a Malaysian destination and open its story. This does not collect a passport stamp.',inputSchema:{type:'object',properties:{destinationId:{type:'string',enum:destinations.map(d=>d.id)}},required:['destinationId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const value=input as {destinationId?:unknown};if(!value||typeof value.destinationId!=='string'||!destinations.some(d=>d.id===value.destinationId)||Object.keys(value).some(k=>k!=='destinationId'))throw new Error('Choose a valid destinationId.');const id=value.destinationId;flushSync(()=>{setSelected(id);setModal('story')});return{destinationId:id,storyOpen:true};}},
  {name:'read_explorer_progress',description:'Read the selected destination, collected stamps, and best quiz score on this device.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Provide an empty object.');return{...currentState.current.progress,selectedDestination:currentState.current.selected};}}];
  for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[]);
 const place=destinations.find(d=>d.id===selected)!;const collected=progress.stamps.includes(selected);
 const openStory=(id:string)=>{setSelected(id);setModal('story')};const openPassport=()=>{setResetConfirm(false);setModal('passport')};const closeModal=()=>setModal(null);
 const collectStamp=()=>setProgress(current=>({...current,stamps:current.stamps.includes(selected)?current.stamps:[...current.stamps,selected]}));
 const showExplorer=()=>document.getElementById('explore')?.scrollIntoView({behavior:'smooth'});
 return <><a className="skip-link" href="#explore">Skip to explorer</a>
 <header className="site-header"><a className="brand" href="#explore" aria-label="Kita Malaysia home"><span className="brand-mark">k<span>.</span></span><span>kita<span className="brand-light">malaysia</span><small>MANY STORIES. ONE MALAYSIA.</small></span></a><nav aria-label="Main navigation"><button className="nav-active" onClick={showExplorer}><Compass size={17}/>Explore</button><button onClick={()=>document.getElementById('stories')?.scrollIntoView({behavior:'smooth'})}><BookOpen size={17}/>The stories</button><button onClick={()=>setModal('quiz')}>Malaysia quiz <ArrowUpRight size={15}/></button></nav><button className="passport-button" onClick={openPassport}><Bookmark size={17}/>My passport<span>{progress.stamps.length} / 6</span></button></header>
 <main><section className="explorer" id="explore" aria-label="Discover Malaysia"><aside className="intro-panel"><div className="eyebrow"><span/> YOUR NEXT DISCOVERY STARTS HERE</div><h1>A little closer<br/> to <em>Malaysia.</em></h1><p className="intro-copy">Big stories. Small wonders.<br/> Explore the places, people, and traditions that make us, us.</p><div className="chapter-label"><span>CHOOSE A PLACE</span><span>01 — 06</span></div><div className="destination-list">{destinations.map((d,i)=><button className={`destination ${selected===d.id?'selected':''}`} key={d.id} aria-pressed={selected===d.id} onClick={()=>setSelected(d.id)}><span className="destination-index">0{i+1}</span><span><strong>{d.name}</strong><small>{d.category}</small></span>{progress.stamps.includes(d.id)?<Check size={16}/>:<ArrowUpRight size={17}/>}</button>)}</div><div className="aside-note"><Sparkles size={18}/><span>A whole country of connections.<br/><strong>One discovery at a time.</strong></span></div></aside>
 <div className="map-panel"><div className="map-topline"><span className="map-badge"><span/> THE DISCOVERY MAP</span><span className="map-caption">A different perspective on home.</span></div><MalaysiaScene selected={selected} onSelect={setSelected} command={command}/><div className="compass-marker" aria-hidden="true">N<Compass size={33} strokeWidth={1}/></div><div className="map-controls">{[{type:'in',icon:Plus,label:'Zoom in'},{type:'out',icon:Minus,label:'Zoom out'},{type:'reset',icon:RotateCcw,label:'Reset view'}].map(c=><button key={c.type} aria-label={c.label} onClick={()=>setCommand(current=>({type:c.type,key:current.key+1}))}><c.icon size={18}/></button>)}</div><div className="map-hint"><Move size={15}/>Drag to rotate · Pinch to zoom<span>Illustrative landscape</span></div><div className="selected-preview" aria-live="polite"><span className="selected-number">0{destinations.indexOf(place)+1}</span><div><span className="eyebrow-small"><MapPin size={12}/>{place.region}</span><h2>{place.name}</h2><p>{place.teaser}</p></div><button className="discover-button" onClick={()=>openStory(selected)} aria-label={`Discover ${place.name}`}><span>Discover</span><ArrowUpRight size={22}/></button></div></div></section>
 <section id="stories" className="stories-section"><div className="section-title"><div><span className="eyebrow-small">BEYOND THE POSTCARD</span><h2>Every place has a story.</h2></div><p>Get to know a little more.<br/>Take a little Malaysia with you.</p></div><div className="story-grid">{destinations.filter(d=>d.image).map(d=><button className="story-card" key={d.id} onClick={()=>openStory(d.id)}><div className="story-image"><img src={d.image} alt={d.imageAlt} loading="lazy" width="650" height="400"/><span>{d.category}</span><div className="card-arrow"><ArrowUpRight size={22}/></div></div><span className="eyebrow-small">{d.region}</span><h3>{d.title}</h3><p>{d.teaser}</p></button>)}</div></section>
 <section className="quiz-banner"><div className="quiz-banner-icon"><Sparkles size={32} strokeWidth={1.3}/></div><div><span className="eyebrow-small">A QUICK DETOUR</span><h2>How well do you know Malaysia?</h2><p>Five questions. A few surprises. A little more connection.</p></div><button className="primary-button" onClick={()=>setModal('quiz')}>Take the quiz <ArrowUpRight size={19}/></button></section></main>
 <footer><a className="footer-brand" href="#explore">kita malaysia<span>Made of many. Moving as one.</span></a><span>Code. Create. Celebrate Malaysia.</span><div className="footer-links"><button onClick={()=>setModal('credits')}>Sources & photo credits</button><span>MERDEKA WEBFORGE 2026</span></div></footer>
 {modal==='story'&&<Modal onClose={closeModal} label={`${place.name} story`} className="story-modal">{place.image?<div className="modal-photo"><img src={place.image} alt={place.imageAlt} width="700" height="340"/><span>{place.region}</span></div>:<div className="story-title-art" style={{background:place.color}}><span>{place.stamp}</span><small>{place.category}</small></div>}<div className="modal-body"><span className="eyebrow-small">{place.region} <span> / </span>{place.category}</span><h2>{place.title}</h2>{place.story.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<div className="fact-box"><Sparkles size={20}/><div><strong>A little thing to remember</strong><p>{place.fact}</p></div></div><a className="source-link" href={place.source} target="_blank" rel="noopener noreferrer">Read more at {place.sourceName}<ExternalLink size={13}/></a><div className="stamp-actions"><button className={`primary-button ${collected?'stamp-collected':''}`} disabled={collected||!loaded} onClick={collectStamp}>{collected?<Check size={17}/>:<Bookmark size={17}/>} {collected?'Stamp collected':'Collect this stamp'}</button><button className="text-button" onClick={openPassport}>My passport <ArrowRight size={16}/></button></div><div className="stamp-status" aria-live="polite">{collected?`${place.name} is now part of your journey.`:'Read the story, keep a little memory.'}</div></div></Modal>}
 {modal==='passport'&&<Modal onClose={closeModal} label="My Malaysia explorer passport" className="passport-modal"><div className="passport-heading"><Globe2 size={34} strokeWidth={1.1}/><span className="eyebrow-small">KITA MALAYSIA</span><h2>Your explorer passport.</h2><p>{progress.stamps.length===6?'Six places. So many connections. Your journey is complete.':'A little collection of places, stories, and discoveries.'}</p></div><div className="passport-body"><div className="passport-progress"><span>{progress.stamps.length} of 6 discoveries</span><strong>{progress.stamps.length===6?'MALAYSIA EXPLORER':'THE JOURNEY CONTINUES'}</strong></div><div className="progress-track"><span style={{width:`${progress.stamps.length/6*100}%`}}/></div><div className="stamps-grid">{destinations.map((d,i)=>{const earned=progress.stamps.includes(d.id);return <button className={`stamp ${earned?'earned':''}`} key={d.id} style={{'--stamp-color':d.color,'--stamp-rotation':`${i%2?3:-3}deg`} as React.CSSProperties} aria-label={`${d.name}: ${earned?'collected':'not collected'}. Open story.`} onClick={()=>openStory(d.id)}><span className="stamp-circle"><small>MALAYSIA</small><strong>{d.stamp}</strong><small>{earned?'DISCOVERED':'TO DISCOVER'}</small></span><span>{d.name}</span>{earned&&<Check size={14}/>}</button>})}</div><div className="passport-quiz"><Award size={23}/><div><strong>{progress.best===null?'A curious mind deserves a challenge.':`Best quiz score: ${progress.best} / 5`}</strong><p>{progress.best===null?'Complete the quiz to add your score.':'Keep exploring. There’s always more to discover.'}</p></div><button className="text-button" onClick={()=>setModal('quiz')}>{progress.best===null?'Try quiz':'Try again'}<ArrowUpRight size={17}/></button></div><p className="storage-note">{storageAvailable?'Saved on this browser. No account needed.':'Browser storage is unavailable. Your progress lasts until this page closes.'}</p>{resetConfirm?<div className="reset-confirm"><span>Clear your stamps and quiz score on this browser?</span><button onClick={()=>{setProgress({stamps:[],best:null});setResetConfirm(false)}}>Yes, start fresh</button><button onClick={()=>setResetConfirm(false)}>Keep my passport</button></div>:<button className="reset-button" disabled={progress.stamps.length===0&&progress.best===null} onClick={()=>setResetConfirm(true)}>Start a fresh passport</button>}</div></Modal>}
 {modal==='quiz'&&<Modal onClose={closeModal} label="Malaysia quiz"><Quiz onComplete={score=>setProgress(current=>({...current,best:Math.max(current.best??0,score)}))} onPassport={openPassport}/></Modal>}
 {modal==='credits'&&<Modal onClose={closeModal} label="Sources and photo credits"><div className="modal-body credits-body"><span className="eyebrow-small">WITH CURIOSITY & CARE</span><h2>Stories with sources.</h2><p>This is a student exploration project. The 3D landscape is a playful illustration, not a geographic or border map. Six stories are a starting point, not a complete portrait of Malaysia’s many communities.</p><h3>Learn a little more</h3><ul className="source-list">{destinations.map(d=><li key={d.id}><a href={d.source} target="_blank" rel="noopener noreferrer">{d.name} — {d.sourceName}<ExternalLink size={13}/></a></li>)}</ul><h3>Photography</h3>{credits.map(c=><div className="photo-credit" key={c.author}><a href={c.source} target="_blank" rel="noopener noreferrer">{c.title}<ExternalLink size={13}/></a><p>Photo by {c.author}. {c.licenseUrl?<a href={c.licenseUrl} target="_blank" rel="noopener noreferrer">{c.license}</a>:c.license}. {c.note}</p></div>)}<p className="credits-note">Original 3D scene made with Three.js. This independent project is not an official tourism service.</p></div></Modal>}
 </>;
}

