export type Destination = {id:string; name:string; region:string; category:string; title:string; teaser:string; story:string[]; fact:string; source:string; sourceName:string; color:string; stamp:string; image?:string; imageAlt?:string; credit?:string; imageSource?:string};
export const destinations:Destination[] = [
 {id:'kl',name:'Kuala Lumpur',region:'Kuala Lumpur',category:'Innovation',title:'Rooted in culture. Reaching for the sky.',teaser:'A familiar skyline with a distinctly Malaysian story.',story:['The PETRONAS Twin Towers bring a Malaysian identity to a modern skyline. Their floor plan draws on an eight-pointed star, a geometric form associated with Islamic design.','The two towers are linked by a skybridge. In our miniature city, they stand for a simple idea: a shared future can grow from the things that make us unique.'],fact:'Look closely: the tower design begins with two overlapping squares.',source:'https://www.malaysia.travel/explore/petronas-twin-tower',sourceName:'Tourism Malaysia',color:'#2761c3',stamp:'KL',image:'/images/kuala-lumpur.jpg',imageAlt:'Kuala Lumpur skyline with the Petronas Twin Towers'},
 {id:'penang',name:'George Town',region:'Penang',category:'Living heritage',title:'Every street has more than one story.',teaser:'Shophouses, shared streets, and generations of exchange.',story:['George Town grew through trade and the meeting of communities. Its streets hold shophouses, places of worship, and living traditions that reflect centuries of cultural exchange.','Together with Melaka, George Town is recognised by UNESCO as a historic city of the Straits of Malacca. Heritage here is lived every day, in neighbourhoods, businesses, and shared spaces.'],fact:'George Town and Melaka share one UNESCO World Heritage listing.',source:'https://whc.unesco.org/en/list/1223/',sourceName:'UNESCO World Heritage Centre',color:'#b86d3d',stamp:'PG',image:'/images/george-town.jpg',imageAlt:'Colourful historic shophouses in George Town, Penang'},
 {id:'melaka',name:'Melaka',region:'Melaka',category:'Living heritage',title:'A meeting place through the centuries.',teaser:'Follow the stories of a historic trading city.',story:['Melaka’s position along a major trading route brought people, languages, and ideas together. Its built heritage reflects successive periods of Malay, Portuguese, Dutch, and British influence.','Its story is also one of living communities. Exploring with curiosity means looking beyond monuments to the customs, food, and daily lives that keep the city’s heritage alive.'],fact:'Melaka and George Town were inscribed on the UNESCO World Heritage List in 2008.',source:'https://whc.unesco.org/en/list/1223/',sourceName:'UNESCO World Heritage Centre',color:'#bc5c4a',stamp:'MK'},
 {id:'kelantan',name:'Kelantan',region:'Kelantan',category:'Art & craft',title:'Where craftsmanship takes flight.',teaser:'Meet the wau bulan, a craft shaped by wind and imagination.',story:['The wau bulan is a traditional Malaysian kite strongly associated with Kelantan. Its name refers to the crescent-like form of its lower section.','Making a wau takes patient handwork: a light bamboo frame supports carefully decorated surfaces. Each kite carries both an eye for balance and a tradition of ornamental design.'],fact:'“Bulan” means moon in Malay; the name refers to the kite’s crescent shape.',source:'https://ebrochures.malaysia.travel/en/malaysia-travel-guide/kelantan/',sourceName:'Tourism Malaysia',color:'#8a579d',stamp:'KT'},
 {id:'sabah',name:'Mount Kinabalu',region:'Sabah',category:'Nature',title:'A mountain. A world of life.',teaser:'Discover the remarkable landscapes of Kinabalu Park.',story:['Kinabalu Park protects a remarkable range of habitats in Sabah, from tropical lowlands to alpine environments. This change in altitude supports exceptional plant diversity.','The mountain is also meaningful to local communities. Appreciating this landscape means respecting its living cultures and the ecosystems that make it so special.'],fact:'Kinabalu Park became a UNESCO World Heritage Site in 2000.',source:'https://whc.unesco.org/en/list/1012/',sourceName:'UNESCO World Heritage Centre',color:'#497661',stamp:'SB',image:'/images/kinabalu.jpg',imageAlt:'Mount Kinabalu rising above the green landscape of Kundasang'},
 {id:'sarawak',name:'Sarawak',region:'Sarawak',category:'Community',title:'Different doors. A shared space.',teaser:'Explore the idea of community through longhouse traditions.',story:['Longhouses are associated with several Indigenous communities in Sarawak, with traditions and designs that differ between communities. Many bring family living spaces together with a shared communal area.','They offer one way to think about unity: a place for individual households alongside a place to gather. Sarawak’s cultures are diverse, and no single building or tradition represents them all.'],fact:'Sarawak’s longhouse traditions vary between communities; there is no single universal design.',source:'https://www.sarawaktourism.com/web/stories/story-view/our-people-orang-ulu',sourceName:'Sarawak Tourism Board',color:'#a3743d',stamp:'SW'},
];
export const questions = [
 {question:'Which two cities share a UNESCO World Heritage listing?',options:['Kuala Lumpur and Kuching','Melaka and George Town','Ipoh and Johor Bahru'],answer:1,explanation:'Melaka and George Town are listed together as historic cities of the Straits of Malacca.'},
 {question:'The word “bulan” in wau bulan means…',options:['Moon','Wind','Bird'],answer:0,explanation:'Bulan means moon in Malay. The kite’s lower section has a crescent-like shape.'},
 {question:'Where is Kinabalu Park?',options:['Sarawak','Pahang','Sabah'],answer:2,explanation:'Kinabalu Park is in Sabah, in Malaysian Borneo.'},
 {question:'What helps make Kinabalu Park so rich in plant life?',options:['Only one type of habitat','A wide range of altitudes and habitats','Its city gardens'],answer:1,explanation:'Its habitats range from tropical lowlands to alpine environments, supporting exceptional diversity.'},
 {question:'Which statement best describes Sarawak’s longhouses?',options:['Every community uses the same design','They belong only to the past','Traditions and designs vary between communities'],answer:2,explanation:'Sarawak is culturally diverse. Longhouse traditions vary, and many remain part of contemporary life.'},
];

